### PR TITLE
MX-581 Re-broadcast all messages received

### PR DESCRIPTION
**Pull request by gaastonsr**
Updated the `_handleMessage` function to re-broadcast all messages received.

### CODE REVIEW

**Comment by ttacon** [comment]
Why is this necessary? This removes the ability to later have message specific transforms - from the PR I'm guessing you're having an issue with the `connected` event (otherwise this behaviour already exists)?

**Comment by gaastonsr** [comment]
It still works the same, the only difference is that `added`, `changed` and `removed` events are broadcasted too.

**Comment by wearhere** [comment]
@ttacon it's opening the publication client up for proxying, see https://github.com/mixmaxhq/emailer-chrome-extension-source/pull/2559 and https://github.com/mixmaxhq/app/pull/4242. (Btw @gaastonsr it would have been nice to provide such description :) However please hold off on commenting on that approach, Gaston is writing a discussion doc.

**Comment by gaastonsr** [comment]
Closing in favor of new implementation.

**Pull request closed without merging**
